name: Minio

on:
  push:
    branches: [ main, minio-tests ]
  pull_request:
    branches: [ main ]

jobs:
  minio:
    name: Run Tests against Minio
    runs-on: ubuntu-latest
    env:
      MINIO_ACCESS_KEY: citest
      MINIO_SECRET_KEY: citest_secret_key
      MINIO_ADMIN_ACCESS_KEY: minioadmin
      MINIO_ADMIN_SECRET_KEY: minioadmin
      BUCKET_NAME: testbucket
    services:
      minio:
        image: bitnami/minio
        ports:
          - 9000:9000
        env:
          MINIO_ACCESS_KEY: ${{ env.MINIO_ADMIN_ACCESS_KEY }}
          MINIO_SECRET_KEY: ${{ env.MINIO_ADMIN_SECRET_KEY }}
        volumes:
          - ${{ github.workspace }}/data:/data
        options: '--name=minio --health-cmd "curl http://localhost:9000/minio/health/live"'
    steps:
      # - name: Setup minio server
      #   run: |
      #     docker run -d -p 9000:9000 --name minio \
      #                -e "MINIO_ACCESS_KEY=${{ env.MINIO_ADMIN_ACCESS_KEY }}" \
      #                -e "MINIO_SECRET_KEY=${{ env.MINIO_ADMIN_SECRET_KEY }}" \
      #                -v ${{ github.workspace }}/data:/data \
      #                -v ${{ github.workspace }}/config:/root/.minio \
      #                minio/minio server /data
      - name: Download mc cli
        run: |
          wget -O /usr/local/bin/mc https://dl.min.io/client/mc/release/linux-amd64/mc
          chmod +x /usr/local/bin/mc
      - name: Setup Minio Admin CLI
        run: |
          mc alias set ghactions http://localhost:9000 ${{ env.MINIO_ADMIN_ACCESS_KEY }} ${{ env.MINIO_ADMIN_SECRET_KEY }}
      - name: Setup CI Bucket
        run: |
          mc mb -p ghactions/${{ env.BUCKET_NAME }}
      - name: Setup CI User
        run: |
          mc admin user add ghactions ${{ env.MINIO_ACCESS_KEY }} ${{ env.MINIO_SECRET_KEY }}
          cat > /tmp/policy.json << 'EOF'
          {
              "Version": "2012-10-17",
              "Statement": [
                  {
                      "Effect": "Allow",
                      "Action": [
                          "s3:*"
                      ],
                      "Resource": [
                          "arn:aws:s3:::${{ env.BUCKET_NAME }}/*",
                          "arn:aws:s3:::${{ env.BUCKET_NAME }}"
                      ]
                  }
              ]
          }
          EOF
          mc admin policy add ghactions cipolicy /tmp/policy.json
          mc admin policy set ghactions cipolicy user=${{ env.MINIO_ACCESS_KEY }}
          mc admin user info ghactions ${{ env.MINIO_ACCESS_KEY }}
      - name: Run Tests against minio
        run: |
          echo "Here be dragons!"